version: '3'

services:
  frontend:
    image: nginx
    ports: 
      - 8080:80
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/index.html:/usr/share/nginx/html/index.html
    
    restart: always
  backend:
    build: ./app
    volumes:
      - ./app:/app/
    ports:
      - 5000:5000
    command: uwsgi --ini /app/api.ini
